export const articles={ko:[
{slug:"exam-overview",category:"시험 구조",title:"건설안전기사 필기·실기 구조 한눈에 보기",description:"5과목 100문항 필기와 필답형·작업형 복합 실기를 분리해 준비합니다.",sections:[["필기는 5과목 100문항","과목별 20문항을 30분씩 풀어 총 150분입니다. 모든 과목의 바닥 점수와 전체 평균을 함께 관리해야 합니다."],["실기는 건설안전실무","Q-Net은 필답형 90분 60점과 작업형 약 50분 40점의 복합형으로 안내합니다."],["필기는 과락과 평균을 동시에 봅니다","각 과목 40점 이상이면서 전 과목 평균 60점 이상이어야 합니다. 한 과목의 과락은 평균 점수로 보완되지 않습니다."],["실기는 60점 이상입니다","실기 합격선은 100점 만점 60점입니다. 세부 일정과 시행 방식은 접수 전 Q-Net 최신 공고를 다시 확인하세요."]]},
{slug:"five-subject-plan",category:"필기 전략",title:"필기 5과목을 과락 없이 배분하는 법",description:"재해 예방부터 현장 안전관리까지 약점 과목을 먼저 안정화합니다.",sections:[["진단 결과를 과목별로 분리합니다","100문항 총점만 보지 말고 5과목 각각의 정답률을 기록해 40점 미만 위험부터 찾습니다."],["공통 개념을 연결합니다","위험성평가, 보호구, 가설구조와 작업계획처럼 여러 과목에 반복되는 개념을 한 기준표로 묶습니다."],["재료와 시공은 공정 흐름으로 봅니다","재료 특성과 시공 순서를 연결하면 단순 암기보다 결함과 위험의 원인을 설명하기 쉽습니다."],["150분 모의고사로 전환을 연습합니다","30분마다 과목이 바뀌는 조건을 재현해 계산 문제와 규정 문제의 시간 배분을 확인하세요."]]},
{slug:"prevention-education",category:"재해 예방",title:"산업재해 예방과 안전보건교육을 원인 사슬로 공부하기",description:"사고 원인, 관리 조직, 교육과 보호 대책을 하나의 예방 흐름으로 연결합니다.",sections:[["사고를 결과부터 거슬러 봅니다","재해 결과에서 직접 원인, 불안전한 상태와 행동, 관리적 원인까지 역추적합니다."],["대책은 위험 제거부터 시작합니다","제거·대체, 공학적 대책, 관리적 대책, 개인보호구 순으로 더 근본적인 조치를 먼저 검토합니다."],["역할과 책임을 상황에 붙입니다","사업주, 관리감독자와 안전보건 관계자의 의무를 추상적인 직책이 아니라 실제 작업 장면과 연결하세요."],["교육은 대상·시기·내용을 함께 외웁니다","누가 언제 어떤 위험을 배우는지 세 요소를 한 문장으로 정리하면 비슷한 교육 유형을 구분할 수 있습니다."]]},
{slug:"ergonomics-risk-assessment",category:"인간공학·위험성평가",title:"작업자 행동과 위험성평가를 판단 순서로 익히기",description:"사람과 작업의 불일치를 찾아 위험 감소 대책으로 이어갑니다.",sections:[["작업을 사람에게 맞춥니다","자세, 반복, 힘, 작업 높이, 표시와 조작의 관계에서 오류와 부담을 키우는 조건을 찾습니다."],["평가 절차를 고정합니다","사전 준비, 유해·위험요인 파악, 위험성 결정, 감소 대책 수립·실행, 기록의 순서를 반복하세요."],["가능성과 중대성을 나눕니다","사고가 일어날 가능성과 일어났을 때의 피해를 별도로 평가한 뒤 허용 여부를 판단합니다."],["개선 뒤 잔여 위험을 확인합니다","대책이 새로운 위험을 만들지는 않았는지, 남은 위험을 작업자에게 어떻게 알릴지까지 검토하세요."]]},
{slug:"construction-materials",category:"건설재료",title:"건설재료를 성질·시험·결함으로 연결하기",description:"콘크리트·강재·목재의 특성이 시공 품질과 안전에 미치는 영향을 정리합니다.",sections:[["재료의 성질을 하중과 환경에 붙입니다","강도, 탄성, 내구성, 수분과 온도 영향을 실제 구조 조건과 연결합니다."],["시험값이 의미하는 바를 설명합니다","슬럼프, 압축강도와 재료 시험 결과를 단순 숫자가 아니라 품질 판단의 근거로 이해하세요."],["배합과 양생의 결과를 추적합니다","재료 비율, 운반, 타설, 다짐과 양생 조건이 균열·공극·강도 저하로 이어지는 경로를 봅니다."],["보관 상태도 품질의 일부입니다","시멘트, 강재와 목재의 현장 보관 조건이 열화와 시공 위험을 키우지 않는지 확인합니다."]]},
{slug:"construction-methods",category:"건설시공",title:"건설시공을 공정 순서와 위험 지점으로 정리하기",description:"토공·기초·철근콘크리트·철골 공정을 선후 관계로 학습합니다.",sections:[["선행 조건부터 확인합니다","후속 공정 전에 지반, 가설 구조, 자재와 작업 공간이 준비됐는지 확인하는 습관을 들입니다."],["토공은 지반과 배수를 함께 봅니다","굴착 깊이, 토질, 지하수와 인접 구조물이 흙막이와 굴착면 안정에 미치는 영향을 연결하세요."],["골조는 하중 전달을 추적합니다","거푸집동바리, 철근, 콘크리트와 철골 접합부에서 시공 중 하중이 어디로 전달되는지 봅니다."],["해체는 시공의 역순이 아닙니다","강도 발현, 지지 상태와 주변 작업을 확인해 해체 순서와 출입 통제를 별도로 계획해야 합니다."]]},
{slug:"site-safety-management",category:"건설공사 안전관리",title:"추락·붕괴·양중 위험을 현장 점검표로 바꾸기",description:"사고 유형마다 위험 구역, 방호 설비와 작업계획을 구체화합니다.",sections:[["추락은 단부와 개구부부터 찾습니다","작업발판, 이동 통로와 개구부에서 안전난간·덮개·추락방호망의 설치와 유지 상태를 확인합니다."],["붕괴는 하중과 지지 조건을 봅니다","비계, 거푸집동바리와 굴착면에 작용하는 하중, 연결부와 지반 조건을 함께 검토합니다."],["양중은 작업반경을 통제합니다","정격하중, 와이어로프·훅 상태, 신호 체계와 출입 금지 구역을 하나의 작업계획으로 묶습니다."],["동시 작업과 기상을 반영합니다","강풍·강우·조도와 상하 동시 작업이 기존 계획을 바꿀 조건인지 작업 전 다시 판단하세요."]]},
{slug:"written-response",category:"필답형 실기",title:"필답형 답안을 조건·위험·대책으로 쓰기",description:"90분 동안 요구 개수와 법적 표현을 놓치지 않는 답안 구조를 만듭니다.",sections:[["요구 동사와 개수를 먼저 표시합니다","설명, 열거, 계산, 조치와 원인 중 무엇을 몇 가지 요구하는지 문제에 표시합니다."],["답은 한 위험에 한 대책으로 씁니다","서로 다른 위험과 대책을 한 문장에 섞지 말고 대응 관계가 보이도록 분리하세요."],["숫자는 단위와 적용 조건을 붙입니다","기준 수치만 쓰지 말고 어느 설비·작업·상황에 적용되는지 함께 적습니다."],["마지막 검토는 누락 중심입니다","중복 답, 주체 없는 문장, 단위와 요구 개수 누락을 빠르게 확인합니다."]]},
{slug:"task-analysis",category:"작업형 실기",title:"작업형 장면에서 위험요인을 빠르게 찾는 순서",description:"사람·설비·환경·작업 방법을 훑어 50분 안에 구체적인 판단을 만듭니다.",sections:[["사람의 위치부터 봅니다","추락 가능 높이, 장비 작업반경, 낙하물 아래와 차량 동선에 사람이 들어가 있는지 찾습니다."],["설비와 방호 상태를 확인합니다","난간, 덮개, 방호망, 지지부와 연결부가 설치 목적에 맞게 유지되는지 봅니다."],["작업 방법과 순서를 읽습니다","인양, 해체, 굴착과 고소 작업이 승인된 계획과 신호 체계에 따라 진행되는지 판단합니다."],["대책은 관찰 장면과 직접 연결합니다","막연한 주의보다 출입 통제, 작업 중지, 보강, 방호 설비 설치처럼 해당 위험을 줄이는 조치를 적으세요."]]},
{slug:"eight-week-plan",category:"학습 계획",title:"8주 필기·실기 연결 계획",description:"필기 개념을 현장 장면과 실기 답안으로 바꾸는 반복 일정을 만듭니다.",sections:[["1주는 진단과 시험 구조","5과목 진단으로 과락 위험을 찾고 필기·실기 시간과 배점을 정확히 기록합니다."],["2~5주는 과목별 공정 지도","매주 한두 과목씩 공정, 재료, 위험, 사고 결과와 방지 대책을 한 장에 연결합니다."],["6~7주는 100문항과 실기 답안","필기 모의고사 뒤 틀린 개념을 필답형 문장과 작업형 장면 분석으로 다시 표현합니다."],["8주는 실제 시간 재현","150분 필기, 90분 필답형과 약 50분 작업형 조건을 나눠 재현하고 반복 누락만 압축 복습합니다."]]}
],en:[
{slug:"exam-overview",category:"Format",title:"Construction Safety Engineer exam at a glance",description:"Prepare separately for the 100-item written stage and combined practical.",sections:[["Written: 100 items across five subjects","Each subject has 20 items and 30 minutes, for a total of 150 minutes."],["Practical: Construction Safety Practice","Q-Net lists a 90-minute written-response part worth 60 and an approximately 50-minute task part worth 40."],["Written uses both floors and an average","You need at least 40 in every subject and an overall average of at least 60."],["Practical requires 60","The practical pass mark is 60 out of 100. Recheck current Q-Net instructions before registration."]]},
{slug:"five-subject-plan",category:"Written strategy",title:"Balance five subjects without a floor failure",description:"Stabilise weak subjects from prevention through site safety management.",sections:[["Track results by subject","A total score can hide a subject below 40, so keep five separate accuracy records."],["Connect shared concepts","Use one reference for risk assessment, PPE, temporary structures and work planning across subjects."],["Study materials through process","Link material properties to construction order, defects and safety outcomes."],["Practise the 150-minute rhythm","Reproduce subject changes every 30 minutes and adjust time for calculation and rule questions."]]},
{slug:"prevention-education",category:"Prevention",title:"Study prevention and safety education as a cause chain",description:"Connect incident causes, management roles, training and controls.",sections:[["Work backward from the loss","Trace the event to direct causes, unsafe conditions or actions and management causes."],["Start controls with hazard removal","Prefer elimination and substitution, then engineering, administrative controls and PPE."],["Attach responsibility to a scene","Learn employer, supervisor and safety roles through concrete work situations."],["Match training to people and timing","Remember who receives each training type, when it occurs and what it covers."]]},
{slug:"ergonomics-risk-assessment",category:"Ergonomics and risk",title:"Use a repeatable risk-assessment sequence",description:"Find mismatches between people and work, then select controls.",sections:[["Fit work to the person","Observe posture, repetition, force, work height, displays and controls."],["Fix the assessment order","Prepare, identify hazards, determine risk, implement reduction measures and record the result."],["Separate likelihood and severity","Judge them independently before applying the workplace acceptance rule."],["Check residual risk","After a change, look for remaining and newly introduced risks and communicate them."]]},
{slug:"construction-materials",category:"Materials",title:"Connect material properties, tests and defects",description:"Understand how concrete, steel and timber affect quality and safety.",sections:[["Attach properties to load and environment","Relate strength, stiffness, durability, moisture and temperature to site conditions."],["Explain what test values mean","Treat slump, compressive strength and other results as quality decisions rather than isolated numbers."],["Trace mix and curing outcomes","Connect proportioning, transport, placement, compaction and curing to voids, cracks and strength loss."],["Include storage conditions","Check whether site storage can degrade cement, steel or timber before use."]]},
{slug:"construction-methods",category:"Construction methods",title:"Map construction order and danger points",description:"Learn earthwork, foundations, concrete and steel by dependency.",sections:[["Check prerequisites first","Confirm ground, temporary works, materials and workspace before the next process starts."],["Read soil and drainage together","Relate excavation depth, soil, groundwater and adjacent structures to support stability."],["Trace load during frame work","Follow temporary loads through falsework, reinforcement, concrete and steel connections."],["Plan dismantling separately","Strength gain, support and nearby work determine a safe removal sequence."]]},
{slug:"site-safety-management",category:"Site safety",title:"Turn fall, collapse and lifting hazards into checks",description:"Define danger zones, protection and work planning for each incident type.",sections:[["Start with edges and openings","Check platforms, access, guardrails, covers and safety nets."],["Review load and support","Assess scaffolds, falsework and excavations with connections, ground and imposed loads."],["Control the lifting radius","Combine rated load, rope and hook condition, signalling and exclusion zones."],["Include weather and simultaneous work","Wind, rain, lighting and work above or below may require a changed plan."]]},
{slug:"written-response",category:"Written practical",title:"Write condition, hazard and control answers",description:"Protect requested counts and technical meaning through the 90-minute response part.",sections:[["Mark the verb and count","Identify whether the question asks for explanation, causes, calculations, controls or a list."],["Use one control for one hazard","Keep different hazards and controls in separate, visible relationships."],["Attach units and scope to numbers","State which equipment, task or condition a limit applies to."],["Review omissions first","Check duplicates, missing actors, units and required answer counts."]]},
{slug:"task-analysis",category:"Task practical",title:"Scan a work scene for hazards in order",description:"Review people, equipment, environment and method within the 50-minute task part.",sections:[["Locate people first","Find workers at height, under suspended loads, inside equipment radii or vehicle routes."],["Inspect protection","Check guardrails, covers, nets, supports and connections against their intended function."],["Read method and sequence","Assess whether lifting, demolition, excavation and elevated work follow a controlled plan."],["Match each control to the scene","Prefer exclusion, stopping, reinforcement or installed protection over vague caution."]]},
{slug:"eight-week-plan",category:"Study plan",title:"An eight-week written-to-practical plan",description:"Convert written concepts into scene analysis and scorable practical answers.",sections:[["Week 1: diagnose and map the format","Find subject-floor risks and record exact timings and marks."],["Weeks 2–5: build process maps","Connect process, material, hazard, consequence and control for one or two subjects each week."],["Weeks 6–7: full written and practical answers","Rewrite mock-test misses as written responses and task-scene judgments."],["Week 8: reproduce time limits","Run 150-minute written, 90-minute response and approximately 50-minute task sessions."]]}
]};
